Reworked from example

diff --git a/opt/recompose b/opt/recompose
--- a/opt/recompose
+++ b/opt/recompose
@@ -1,7 +1,15 @@
 #!/usr/bin/env bash
 
-# fail fast
-set -eu
+# don't fail fast
+#set -eu
+
+if [ -f .heroku/bin/web ]; then
+  eval "./bin/web &"
+  pid=$!
+  trap "kill -9 $pid; exit" SIGKILL
+else
+  echo "No .heorku/bin/web file found!"
+fi
 
 # create netrc
 cat >> $HOME/.netrc <<EOF
@@ -21,16 +29,27 @@ while read app_release; do
     app=${app_release_array[0]}
     release=${app_release_array[1]}
 
-    slug_id=$(curl -s -n https://api.heroku.com/apps/$app/releases/$release \
+    slug_id=$(curl --retry 3 -s -n https://api.heroku.com/apps/$app/releases/$release \
       -H "Accept: application/vnd.heroku+json; version=3" | \
       python -c 'import json,sys;obj=json.load(sys.stdin);print obj["slug"]["id"]')
 
-    slug_url=$(curl -s -n https://api.heroku.com/apps/$app/slugs/$slug_id \
-      -H "Accept: application/vnd.heroku+json; version=3" | \
-      python -c 'import json,sys;obj=json.load(sys.stdin);print obj["blob"]["url"]')
+    if [ -n "$slug_id" ]; then
+      slug_url=$(curl --retry 3 -s -n https://api.heroku.com/apps/$app/slugs/$slug_id \
+        -H "Accept: application/vnd.heroku+json; version=3" | \
+        python -c 'import json,sys;obj=json.load(sys.stdin);print obj["blob"]["url"]')
 
-    echo "--> Downloading slug ${slug_id} for ${app}"
-    curl -s -L "${slug_url}" | tar xzm --strip-components=2
+      if [ -n "$slug_url" ]; then
+        echo "--> Downloading slug ${slug_id} for ${app}"
+        [ -n "$RECOMPOSE_DIR" ] && mkdir -p $RECOMPOSE_DIR
+        curl --retry 3 -s -L "${slug_url}" | \
+            tar xzm --strip-components=2 -C ${RECOMPOSE_DIR:-.} 2>&1 | \
+            grep -v "Ignoring unknown extended header keyword"
+      else
+        echo "--> ERROR: could not find slug $slug_id for $app_release"
+      fi
+    else
+      echo "--> ERROR: could not find release v${release} for ${app}"
+    fi
   else
     echo "--> Done"
   fi
@@ -38,8 +57,4 @@ done </app/Appfile
 
 rm $HOME/.netrc
 
-if [ -f bin/web ]; then
-  ./bin/web
-else
-  echo "No bin/web file found!"
-fi
+while kill -0 $pid; do sleep 5; done
